version: '3.8'

services:
  symbiota:
    build:
      context: ./ubuntuContainer
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /home/herbaria/running-symbiota:/var/www/html/symbiota
    depends_on:
      - symbiota-db
      - ocr-server

  symbiota-db:
    build:
      context: ./mysqlContainer
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symbiota
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - /home/herbaria/running-containers/db-backups:/source

  ocr-server:
    build:
      context: ./flaskContainer
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /home/herbaria/running-containers/sample-ocr:/data

volumes:
  mysql-data: